# Generated by Django 5.0.7 on 2024-08-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='langauges_used',
            new_name='languages_used',
        ),
    ]
