# Generated by Django 5.0.7 on 2024-08-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_langauges_used_project_languages_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.CharField(max_length=200),
        ),
    ]
