# Generated by Django 5.0.7 on 2024-08-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code_link',
            field=models.CharField(default='placeholder', max_length=200),
        ),
    ]
