# Generated by Django 5.0.7 on 2024-08-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_code_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.CharField(default='placeholder', max_length=300),
        ),
    ]
