# Generated by Django 5.0.7 on 2024-08-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('thumbnail', models.CharField(default='placeholder', max_length=200)),
                ('code_link', models.CharField(default='placeholder', max_length=200)),
                ('course_link', models.CharField(max_length=200)),
            ],
        ),
    ]
